name: CI Back-End Compile
on: 
  push:
    brances:
      - 'main'
    paths:
      - 'sgcmapi/**' # * significa todos os diretorios, ** sao todos os diretorios e sub-diretorios
  workflow_dispatch:
  pull_request:
    paths:
      - 'sgcmapi/**'
  workflow_call:
      
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Mavem Compile
        working-directory: sgcmapi/
        run: mvn compile 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
       uses: actions/checkout@v4
       - name: Set up JDK 17
       uses: actions/setup-java@v3
       with:
        java-version: '17'
        distribution: 'temurin'
       - name: Mavem test
         working-directory: sgcmapi/
         run: mvn test 