name: CI Back-End
on: 
  push:
    brances:
      - 'main'
    paths:
      - 'sgcmapi/**' # * significa todos os diretorios, ** sao todos os diretorios e sub-diretorios
jobs:
  primeiro-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Mavem Compile/Test
        working-directory: sgcmapi/
        run: mvn compile test